

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: urlshortener-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: urlshortener-frontend
    ports:
      - "3000:3000"  # assuming React app is served on port 80 inside container
    restart: always
    depends_on:
      - backend
