version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: urlshortener-backend
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: urlshortener-frontend
    ports:
      - "80:80"  
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
